### ISSUE TITLE
SNMP trap listener

### ISSUE THREAD

**Issue by ajayit1994** [stephenwvickers/node-net-snmp#30] opened 2017-10-11 14:25 UTC

**Comment by stephenwvickers** [comment] 2017-10-19 07:41
This is a duplicate of #3

**Closed by stephenwvickers** 2017-10-19 07:41 UTC

**Comment by markabrahams** [comment] 2020-01-15 13:31
@ajayit1994 - FYI a trap/inform receiver is now implemented for this library, and is available in the latest NPM (added in v2.1.0). Documentation on using the Receiver is in the README.md:
https://github.com/markabrahams/node-net-snmp
